#speaker:Kuma
這層有兩間練習教室！我們很常待在這裡練習！
#speaker:Karo
之前一直都是自主練習呢。
#speaker:Kuma
啊不妙...我突然想起來我這周的發聲訓練還沒做完。
#speaker:Mizar
欸？那你要先去練習嗎？
#speaker:Karo
如果讓大家現在都去練習就沒有人帶經紀人逛了呢...
#speaker:Karo
小熊快去練習，我們會帶他逛完的。
#speaker:Kuma
嗚。