//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Main/PackUIAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PackUIAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PackUIAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PackUIAction"",
    ""maps"": [
        {
            ""name"": ""TypeControl"",
            ""id"": ""b3e028f8-524d-41d6-84bd-0cefdecb6dde"",
            ""actions"": [
                {
                    ""name"": ""SwitchLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c884d0fc-1a54-4e32-9c71-b85c637e4583"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchRight"",
                    ""type"": ""Button"",
                    ""id"": ""349f9fe4-3c9b-4fa4-8971-6e9d90bba941"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2699f7c-7fa3-44f9-94c4-9a6a6d58a844"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""194a53f3-bd2b-4f0b-bcbd-1972fabb0762"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TypeControl
        m_TypeControl = asset.FindActionMap("TypeControl", throwIfNotFound: true);
        m_TypeControl_SwitchLeft = m_TypeControl.FindAction("SwitchLeft", throwIfNotFound: true);
        m_TypeControl_SwitchRight = m_TypeControl.FindAction("SwitchRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TypeControl
    private readonly InputActionMap m_TypeControl;
    private List<ITypeControlActions> m_TypeControlActionsCallbackInterfaces = new List<ITypeControlActions>();
    private readonly InputAction m_TypeControl_SwitchLeft;
    private readonly InputAction m_TypeControl_SwitchRight;
    public struct TypeControlActions
    {
        private @PackUIAction m_Wrapper;
        public TypeControlActions(@PackUIAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchLeft => m_Wrapper.m_TypeControl_SwitchLeft;
        public InputAction @SwitchRight => m_Wrapper.m_TypeControl_SwitchRight;
        public InputActionMap Get() { return m_Wrapper.m_TypeControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TypeControlActions set) { return set.Get(); }
        public void AddCallbacks(ITypeControlActions instance)
        {
            if (instance == null || m_Wrapper.m_TypeControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TypeControlActionsCallbackInterfaces.Add(instance);
            @SwitchLeft.started += instance.OnSwitchLeft;
            @SwitchLeft.performed += instance.OnSwitchLeft;
            @SwitchLeft.canceled += instance.OnSwitchLeft;
            @SwitchRight.started += instance.OnSwitchRight;
            @SwitchRight.performed += instance.OnSwitchRight;
            @SwitchRight.canceled += instance.OnSwitchRight;
        }

        private void UnregisterCallbacks(ITypeControlActions instance)
        {
            @SwitchLeft.started -= instance.OnSwitchLeft;
            @SwitchLeft.performed -= instance.OnSwitchLeft;
            @SwitchLeft.canceled -= instance.OnSwitchLeft;
            @SwitchRight.started -= instance.OnSwitchRight;
            @SwitchRight.performed -= instance.OnSwitchRight;
            @SwitchRight.canceled -= instance.OnSwitchRight;
        }

        public void RemoveCallbacks(ITypeControlActions instance)
        {
            if (m_Wrapper.m_TypeControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITypeControlActions instance)
        {
            foreach (var item in m_Wrapper.m_TypeControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TypeControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TypeControlActions @TypeControl => new TypeControlActions(this);
    public interface ITypeControlActions
    {
        void OnSwitchLeft(InputAction.CallbackContext context);
        void OnSwitchRight(InputAction.CallbackContext context);
    }
}
