#speaker:Kuma
這層有兩間練習教室！我們很常待在這裡練習！
#speaker:Karo
之前一直都是自主練習呢。
#speaker:Aicor
啊不妙...我這周核心的訓練還沒做。
#speaker:Kuma
欸？你要去練習了嗎～？
#speaker:Karo
如果讓大家現在都去練習就沒有人帶經紀人逛了呢...
#speaker:Karo
艾可你先去練習，我們留下來吧～！
#speaker:Aicor
謝啦。
